### ISSUE TITLE
concorde or pyconcorde dependency error?

### ISSUE THREAD

**Issue by aswarner** [liangxinedu/NeuroLKH#8]
Does test.py use the default package [concorde](https://pypi.org/project/concorde/) that can be installed with pip, or does it use pyconcorde at [https://github.com/jvkersch/pyconcorde](https://github.com/jvkersch/pyconcorde)?

When I build the project and run `python data_generate.py -test` using concorde from pypi, I get the following error: 
```
Traceback (most recent call last):
  File "/home/aswarner/NeuroLKH/data_generate.py", line 2, in <module>
    from concorde.tsp import TSPSolver
  File "/home/aswarner/NeuroLKH/neurenv/lib/python3.11/site-packages/concorde/__init__.py", line 8, in <module>
    from urlparse import urljoin
ModuleNotFoundError: No module named 'urlparse'
```
It appears that the concorde module isn't compatible with python3. Is there a workaround? I also wasn't able to build pyconcorde to try.

**Comment by zuoan7** [comment]
The same issue. Have you resolved it?

**Comment by imyourbug** [comment]
U can clone pyconcorde manually and place concorde directory exactly to import that module.
